### ISSUE TITLE
Anchors for headings don't exist

### ISSUE THREAD

**Issue by scottgonzalez** [johnny-five-io/johnny-five.io#67]
For example, components that require PingFirmata link to http://johnny-five.io/api/proximity/#pingfirmata, which should take you to the PingFirmata heading as https://github.com/rwaldron/johnny-five/wiki/Proximity#pingfirmata does. However, the anchors don't exist, so the hash doesn't take you to the appropriate heading.

**Comment by frxnz** [comment]
c8a387dae7b8340d09ba51e1ed3069482a535b2a fixes this
