### ISSUE TITLE
Homepage board images are very high-resolution PNGs

### ISSUE THREAD

**Issue by kadamwhite** [johnny-five-io/johnny-five.io#77]
![image](https://cloud.githubusercontent.com/assets/442115/11746076/16657f84-9fea-11e5-9279-16713689bbf1.png)

The images for each board on the Johnny Five homepage are high-resolution pngs, which are being displayed scaled down to ~1/10th their native size. Significant page weight gains could be achieved by using smaller images or, probably better yet, using SVGs (since the images are all diagrams)

**Comment by tkellen** [comment]
:+1: @Wilto and I were talking about this yesterday!

**Comment by kadamwhite** [comment]
To clarify the weight issue, **3.4mb** of the page weight currently is images.
![image](https://cloud.githubusercontent.com/assets/442115/11746112/4de7be9a-9fea-11e5-8c6c-04c2cee5f76a.png)

**Comment by tkellen** [comment]
Here's a great doc on how to deal with this:
https://github.com/bocoup/website/wiki/Managing-Images

**Comment by frxnz** [comment]
These are all Fritzing components, so it could just be a matter of re-exporting them from Fritzing as SVGs.

**Comment by tkellen** [comment]
gzipped svgs would be brilliant

**Comment by kadamwhite** [comment]
> These are all Fritzing components

When Francis said they were "fritzing diagrams" I'd totally taken Fritzing as a euphemism...!

**Comment by rwaldron** [comment]
So the problem with the Frizting -> svg suggestion is that that none of these was made directly from fritzing. It would actually be impossible to make these the way they are directly from fritzing, because many are scaled to fit a certain visual sizing style. I've just batch resized the pngs for the time being.

**Comment by rwaldron** [comment]
Size is now 811kb

**Comment by rwaldron** [comment]
https://github.com/bocoup/johnny-five.io/pull/78
